module.exports = [
  {
    id: 1,
    icon: 'laptop',
    name: '网站概览',
    router: '/dashboard',
  },
  {
    id: 2,
    bpid: 1,
    name: '用户管理',
    icon: 'user',
    router: '/user',
  },
  {
    id: 21,
    mpid: -1,
    bpid: 2,
    name: '详细信息',
    router: '/user/:id',
  },
  {
    id: 3,
    bpid: 1,
    name: '商品管理',
    icon: 'shop',
    router: '/goods',
  },
  {
    id: 31,
    mpid: -1,
    bpid: 3,
    name: '详细信息',
    router: '/good/:id',
  },
  {
    id: 4,
    bpid: 1,
    name: 'API测试',
    icon: 'api',
    router: '/request',
  },
  {
    id: 5,
    bpid: 1,
    name: 'UI 组件',
    icon: 'camera-o',
  },
  {
    id: 51,
    bpid: 5,
    mpid: 5,
    name: 'IconFont',
    icon: 'heart-o',
    router: '/UIElement/iconfont',
  },
  {
    id: 52,
    bpid: 5,
    mpid: 5,
    name: 'DataTable',
    icon: 'database',
    router: '/UIElement/dataTable',
  },
  {
    id: 53,
    bpid: 5,
    mpid: 5,
    name: 'DropOption',
    icon: 'bars',
    router: '/UIElement/dropOption',
  },
  {
    id: 54,
    bpid: 5,
    mpid: 5,
    name: 'Search',
    icon: 'search',
    router: '/UIElement/search',
  },
  {
    id: 55,
    bpid: 5,
    mpid: 5,
    name: 'Editor',
    icon: 'edit',
    router: '/UIElement/editor',
  },
  {
    id: 56,
    bpid: 5,
    mpid: 5,
    name: 'layer (Function)',
    icon: 'credit-card',
    router: '/UIElement/layer',
  },
  {
    id: 6,
    bpid: 1,
    name: '数据可视化',
    icon: 'code-o',
  },
  {
    id: 61,
    bpid: 6,
    mpid: 6,
    name: 'LineChart',
    icon: 'line-chart',
    router: '/chart/lineChart',
  },
  {
    id: 62,
    bpid: 6,
    mpid: 6,
    name: 'BarChart',
    icon: 'bar-chart',
    router: '/chart/barChart',
  },
  {
    id: 63,
    bpid: 6,
    mpid: 6,
    name: 'AreaChart',
    icon: 'area-chart',
    router: '/chart/areaChart',
  },
  {
    id: 7,
    bpid: 1,
    name: 'Test Navigation',
    icon: 'setting',
  },
  {
    id: 71,
    bpid: 7,
    mpid: 7,
    name: 'Test Navigation1',
    router: '/navigation/navigation1',
  },
  {
    id: 72,
    bpid: 7,
    mpid: 7,
    name: 'Test Navigation2',
    router: '/navigation/navigation2',
  },
  {
    id: 721,
    bpid: 72,
    mpid: 72,
    name: 'Test Navigation21',
    router: '/navigation/navigation2/navigation1',
  },
  {
    id: 722,
    bpid: 72,
    mpid: 72,
    name: 'Test Navigation22',
    router: '/navigation/navigation2/navigation2',
  },
]
